- date: "2026-06"
  type: service
  text: "TPC @ *CHES'27*."

- date: "2026-06"
  type: service
  text: "TPC @ *HOST'27*."

- date: "2026-06"
  type: service
  text: "TPC @ *USENIX Security'27*."

- date: "2026-05"
  type: service
  text: "TPC @ *DATE'27*."

- date: "2026-05"
  type: service
  text: "TPC @ *S&P'27*."

- date: "2026-04"
  type: service
  text: "TPC @ *ACTIVE workshop, collocated with CCS'26*."

- date: "2026-04"
  type: service
  text: "Workshop chair @ *NDSS'27*, together with [Christophe Hauser](https://faculty-directory.dartmouth.edu/christophe-hauser) and [Giovanni Apruzzese](https://www.giovanniapruzzese.com/)."

- date: "2026-04"
  type: service
  text: "TPC @ *NDSS'27*."

- date: "2026-02"
  type: service
  text: "Session chairs @ *NDSS'26*."

- date: "2025-09"
  type: service
  text: "Co-chairs the [*Top Picks in Hardware and Embedded Security*](https://sites.google.com/view/toppickshardwaresec) collocated with ICCAD 2025."

- date: "2025-06"
  type: service
  text: "TPC @ *USENIX Security'26*."

- date: "2025-06"
  type: service
  text: "TPC @ *CHES'26*."

- date: "2025-04"
  type: service
  text: "TPC @ *NDSS'26*."

- date: "2025-01"
  type: service
  text: "TPC @ *CCS'25*."

- date: "2024-10"
  type: service
  text: "TPC @ *USENIX Security'25*."

- date: "2026-04"
  type: activity
  text: "Organizes [*Focus Session*](https://date26.date-conference.com/programme#FS05) at *DATE'26*."

- date: "2026-02"
  type: activity
  text: "Invited talk at the *Institute of Software, Chinese Academy of Sciences* (Hosted by Si Gao)"

- date: "2025-11"
  type: activity
  text: "Invited talk at the *College of Computer Science and Technology, Zhejiang University* (Hosted by [Fan Zhang](https://person.zju.edu.cn/en/fanzhang))"

- date: "2025-10"
  type: activity
  text: "Organizes [*tutorial*](https://2025.iccad.com/tutorials) at *ICCAD'25*."

- date: "2025-09"
  type: activity
  text: "Organizes the [*HACK@CHES 2025*](https://hackthesilicon.com/hackches25/) collocated with CHES 2025, collaborated with Intel and Texas A&M University."

- date: "2025-03"
  type: activity
  text: "Organizes the [*HACK@DATE 2025*](https://hackthesilicon.com/date25/) collocated with *DATE 2025*, collaborated with Intel and Texas A&M University."

- date: "2024-09"
  type: activity
  text: "Invited talk at the *School of Cyber Science and Technology, Beijing Institute of Technology* (Hosted by [An Wang](https://pure.bit.edu.cn/en/persons/an-wang/))"
